version: '3'
services:
  neovim:
    build: 
      context: .
      args:
        USER_NAME: 'neovim'
        VIM_ENABLE_NODE: 'y'
        VIM_ENABLE_PYTHON: 'y'
        VIM_ENABLE_PYTHON3: 'y'
        VIM_ENABLE_DEIN: ''
        VIM_ENABLE_PACKER: 'y'
        RIPGREP_VERSION: '12.1.1'
        FD_VERSION: '8.2.1'
        BAT_VERSION: '0.18.1'
    volumes:
      - ./nvim:/home/neovim/.config/nvim
    tty: true
    environment:
      - MYVIMRC=/home/ichinose/.config/nvim/init.lua
      # - FZF_DEFAULT_OPTS='--layout=reverse --height=50% --border --ansi'
      # - FZF_DEFAULT_COMMAND='find .'

